<?php
require dirname(__DIR__).'/core/components/shopkeeper4/autoload.php';
require __DIR__.'/FixtureProducts.php';
use Shopkeeper4\{Database,Installer,Store,Decimal,Settings,Cart,Html};
$checks=0;
function eq($a,$b,string $message): void { global $checks;++$checks;if($a!==$b) throw new RuntimeException($message.': '.var_export($a,true).' !== '.var_export($b,true)); }
function fails(callable $fn,string $message): void { global $checks;try{$fn();}catch(Throwable $e){++$checks;return;}throw new RuntimeException('Expected failure: '.$message); }
$pdo=new PDO('sqlite::memory:',null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
$db=new Database($pdo,'test_','sqlite');Installer::install($db);Installer::install($db);
$db->run('CREATE TABLE fixture_stock (id INTEGER PRIMARY KEY, quantity INTEGER NOT NULL)');
$db->run('INSERT INTO fixture_stock VALUES(1,10000),(2,1000)');
$store=new Store($db,new FixtureProducts($db));
eq($store->settings()['version'],1,'Idempotent install');
eq(Decimal::scaled('10,25'),1025,'Decimal comma');eq(Decimal::line(101,1500),152,'Rounding');
fails(fn()=>Decimal::scaled('-1'),'Negative money');fails(fn()=>Decimal::scaled('1e6'),'Exponent');fails(fn()=>Decimal::line(99999999999,100000000),'Overflow');
$settings=$store->settings()['data'];$settings['general']['track_inventory']=true;
$settings['delivery'][0]['price']='50.00';$settings['delivery'][0]['free_from']='200.00';
$settings['currencies'][]=['code'=>'USD','label'=>'USD','rate'=>'100.0000'];
$store->saveSettings($settings,1);fails(fn()=>$store->saveSettings($settings,1),'Settings stale');
$cart=[['product_id'=>1,'quantity'=>'1','selected'=>['size'=>'large'],'price'=>'0.01']];
$quote=$store->quote($cart,'web','RUB',1);eq($quote['total'],15525,'Server price and option');
eq($store->quote($cart,'web','USD',1)['total'],155,'Currency conversion');
eq($store->quote([['product_id'=>1,'quantity'=>'2']],'web','',1)['delivery_fee'],0,'Free delivery');
fails(fn()=>$store->quote([['product_id'=>1,'quantity'=>'0.5']],'web','',1),'Fractional disabled');
fails(fn()=>$store->quote([['product_id'=>7,'quantity'=>'1']],'web','',1),'Unknown product');
fails(fn()=>$store->quote($cart,'mgr','',1),'Context isolation');
fails(fn()=>$store->quote([['product_id'=>1,'selected'=>['size'=>'hacked']]],'web','',1),'Unknown variant');
$input=['fullname'=>'Иван [[!evil]]','email'=>'ivan@example.test','phone'=>'+79990000000'];
fails(fn()=>$store->create($cart,[],'web',0,str_repeat('a',64)),'Required contacts');
$first=$store->create($cart,$input,'web',0,str_repeat('a',64));$id=$first['id'];
eq($first['duplicate'],false,'First checkout');eq($store->create([],$input,'web',0,str_repeat('a',64))['duplicate'],true,'Database idempotency');
eq((int)$db->one('SELECT quantity FROM fixture_stock WHERE id=1')['quantity'],9000,'Reserve once');
$before=(int)$db->one('SELECT COUNT(*) n FROM '.$db->table('orders'))['n'];
fails(fn()=>$store->create([['product_id'=>1,'quantity'=>'1'],['product_id'=>2,'quantity'=>'2']],$input,'web',0,str_repeat('b',64)),'Stock shortage rolls back');
eq((int)$db->one('SELECT COUNT(*) n FROM '.$db->table('orders'))['n'],$before,'No partial order');
eq((int)$db->one('SELECT quantity FROM fixture_stock WHERE id=1')['quantity'],9000,'Stock transaction rollback');
$store->status([$id=>1],5,7);eq((int)$db->one('SELECT quantity FROM fixture_stock WHERE id=1')['quantity'],10000,'Cancel releases');
eq($store->status([$id=>2],5,7),[],'Same status no changes');
$store->status([$id=>2],1,7);eq((int)$db->one('SELECT quantity FROM fixture_stock WHERE id=1')['quantity'],9000,'Reopen reserves');
$other=$store->create([['product_id'=>1,'quantity'=>'1']],$input,'web',0,str_repeat('c',64))['id'];
fails(fn()=>$store->status([$id=>3,$other=>999],5,7),'Atomic bulk conflict');
eq((int)$store->order($id)['status_id'],1,'First bulk change rolled back');
eq((int)$db->one('SELECT quantity FROM fixture_stock WHERE id=1')['quantity'],8000,'Bulk stock rolled back');
$order=$store->order($id);$item=$order['items'][0];$item['price']='100.25';$item['quantity']='3';$item['options'][0]['price']='5.00';
$edit=['version'=>3,'status_id'=>1,'items'=>[$item],'contacts'=>$order['contacts'],'delivery_fee'=>'0'];
$store->update($id,$edit,7);eq((int)$store->order($id)['total'],31575,'Manager totals');
eq((int)$db->one('SELECT quantity FROM fixture_stock WHERE id=1')['quantity'],6000,'Edit stock delta');
fails(fn()=>$store->update($id,$edit,7),'Order version conflict');
$store->remove([$id=>4],7);fails(fn()=>$store->order($id),'Soft removed invisible');
eq((int)$db->one('SELECT quantity FROM fixture_stock WHERE id=1')['quantity'],9000,'Delete release');
eq($store->orders([])['total'],1,'Removed excluded');
eq($store->orders(['query'=>"' OR 1=1 --",'sort'=>'DROP TABLE orders'])['total'],0,'Search injection');
fails(fn()=>$store->orders(['date_from'=>'2026-02-31']),'Invalid date');
fails(fn()=>$store->orders(['date_from'=>'2026-02-10','date_to'=>'2026-02-01']),'Inverted dates');
eq(count($store->stats([])),1,'Statistics');
$session=[];$basket=new Cart($store,'web',$session);fails(fn()=>$basket->verify('bad'),'CSRF');$basket->verify($basket->csrf());
$basket->mutate('add',['product_id'=>1,'quantity'=>'1']);$nonce=$basket->checkoutToken();
$result=$basket->checkout($input+['checkout_token'=>$nonce],0);eq($result['duplicate'],false,'Cart checkout');
eq($basket->checkout($input+['checkout_token'=>$nonce],0)['duplicate'],true,'Cart retry suppresses notifications');
eq(count($basket->view()['items']),0,'Cart cleared');
$basket->mutate('add',['product_id'=>1,'quantity'=>'1']);eq($nonce!==$basket->checkoutToken(),true,'New cart nonce');
fails(fn()=>$basket->mutate('add',['product_id'=>2,'quantity'=>'0.5']),'Invalid cart mutation');eq(count($basket->view()['items']),1,'Cart mutation rollback');
eq(str_contains(Html::escape('[[!evil]]<script>'),'['),false,'MODX tag escaping');
$bad=$store->settings()['data'];$bad['statuses'][0]['color']='red" onclick="x';fails(fn()=>Settings::validate($bad),'Color injection');
$bad=$store->settings()['data'];$bad['statuses'][0]['cancelled']=true;fails(fn()=>$store->saveSettings($bad,2),'Used status semantics');
echo "PASS: $checks checks\n";
